=== dic-case-studies/casa6/casa5/gcwrap/xml/casa.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xsd:schema elementFormDefault="qualified" 
	targetNamespace="urn:Test.Namespace"
	xmlns:xsd="http://www.w3.org/2001/XMLSchema"
	xmlns="urn:Test.Namespace">
	<xsd:element name="casaxml">
		<xsd:complexType>
			<xsd:sequence>
				<xsd:element ref="task" maxOccurs="unbounded"/>
				<xsd:element ref="tool" maxOccurs="unbounded"/>
			</xsd:sequence>
		</xsd:complexType>
	</xsd:element>
	<xsd:element name="tool">
		<xsd:complexType mixed="true">
			<xsd:sequence>
				<xsd:element ref="keyword" minOccurs="0" maxOccurs="unbounded"/>
				<xsd:element ref="code" minOccurs="0"/>
				<xsd:element ref="shortdescription"/>
				<xsd:element ref="description" minOccurs="0"/>
				<xsd:element ref="example" minOccurs="0"/>
				<xsd:element ref="needs" minOccurs="0"/>
				<xsd:element ref="comment" minOccurs="0"/>
				<xsd:element ref="comments" minOccurs="0"/>
				<xsd:element ref="method" maxOccurs="unbounded"/>
			</xsd:sequence>
			<xsd:attribute name="name" type="xsd:string" use="required"/>
			<xsd:attribute name="module" type="xsd:string" use="required"/>
		</xsd:complexType>
	</xsd:element>
	<xsd:element name="method">
		<xsd:complexType mixed="true">
			<xsd:sequence>
				<xsd:element ref="comments" minOccurs="0"/>
				<xsd:element ref="return" minOccurs="0"/>
				<xsd:element ref="keyword" minOccurs="0" maxOccurs="unbounded"/>
				<xsd:element ref="shortdescription" minOccurs="0"/>
				<xsd:element ref="description" minOccurs="0"/>
				<xsd:element ref="output" minOccurs="0"/>
				<xsd:element ref="input" minOccurs="0"/>
				<xsd:element ref="returns" minOccurs="0"/>
				<xsd:element ref="example" minOccurs="0" maxOccurs="unbounded"/>
			</xsd:sequence>
			<xsd:attribute name="type" type="xsd:string" use="required"/>
			<xsd:attribute name="name" type="xsd:string" use="required"/>
			<xsd:attribute name="direction" type="xsd:string"/>
		</xsd:complexType>
	</xsd:element>
	<xsd:element name="example">
		<xsd:complexType mixed="true">
			<xsd:sequence>
				<xsd:element ref="comments" minOccurs="0"/>
				<xsd:element ref="link" minOccurs="0" maxOccurs="unbounded"/>
			</xsd:sequence>
		</xsd:complexType>
	</xsd:element>
	<xsd:element name="returns">
		<xsd:complexType mixed="true">
			<xsd:sequence>
				<xsd:element ref="any" minOccurs="0"/>
				<xsd:element ref="shortdescription" minOccurs="0"/>
				<xsd:element ref="description" minOccurs="0"/>
			</xsd:sequence>
			<xsd:attribute name="type" type="xsd:string"/>
		</xsd:complexType>
	</xsd:element>
	<xsd:element name="input">
		<xsd:complexType>
			<xsd:sequence>
				<xsd:element ref="value" minOccurs="0"/>
				<xsd:element ref="param" minOccurs="0" maxOccurs="unbounded"/>
			</xsd:sequence>
		</xsd:complexType>
	</xsd:element>
	<xsd:element name="description">
		<xsd:complexType mixed="true">
			<xsd:sequence>
				<xsd:element ref="sup" minOccurs="0" maxOccurs="unbounded"/>
				<xsd:element ref="sub" minOccurs="0" maxOccurs="unbounded"/>
				<xsd:element ref="link" minOccurs="0" maxOccurs="unbounded"/>
			</xsd:sequence>
		</xsd:complexType>
	</xsd:element>
	<xsd:element name="shortdescription">
		<xsd:complexType mixed="true">
			<xsd:sequence>
				<xsd:element ref="link" minOccurs="0" maxOccurs="unbounded"/>
			</xsd:sequence>
		</xsd:complexType>
	</xsd:element>
	<xsd:element name="param">
		<xsd:complexType>
			<xsd:sequence>
				<xsd:element ref="allowed" minOccurs="0"/>
				<xsd:element ref="choice" minOccurs="0" maxOccurs="unbounded"/>
				<xsd:element ref="any" minOccurs="0"/>
				<xsd:element ref="description" minOccurs="0"/>
				<xsd:element ref="range" minOccurs="0"/>
				<xsd:element ref="value" minOccurs="0" maxOccurs="unbounded"/>
			</xsd:sequence>
			<xsd:attribute name="type" type="xsd:string" use="required"/>
			<xsd:attribute name="name" type="xsd:string" use="required"/>
			<xsd:attribute name="direction" type="xsd:string"/>
			<xsd:attribute name="units" type="xsd:string"/>
			<xsd:attribute name="mustexist" type="xsd:string"/>
		</xsd:complexType>
	</xsd:element>
	<xsd:element name="value">
		<xsd:complexType mixed="true">
			<xsd:sequence>
				<xsd:element ref="value" minOccurs="0" maxOccurs="unbounded"/>
			</xsd:sequence>
			<xsd:attribute name="type" type="xsd:string"/>
		</xsd:complexType>
	</xsd:element>
	<xsd:element name="any">
		<xsd:complexType>
			<xsd:attribute name="type" type="xsd:string" use="required"/>
			<xsd:attribute name="limittypes" type="xsd:string"/>
		</xsd:complexType>
	</xsd:element>
	<xsd:element name="code">
		<xsd:complexType>
			<xsd:sequence>
				<xsd:element ref="include"/>
				<xsd:element ref="private"/>
			</xsd:sequence>
		</xsd:complexType>
	</xsd:element>
	<xsd:element name="private">
		<xsd:complexType>
			<xsd:sequence>
				<xsd:element ref="include"/>
			</xsd:sequence>
		</xsd:complexType>
	</xsd:element>
	<xsd:element name="include" type="xsd:string"/>
	<xsd:element name="keyword" type="xsd:string"/>
	<xsd:element name="choice" type="xsd:string"/>
	<xsd:element name="link">
		<xsd:complexType>
			<xsd:simpleContent>
				<xsd:extension base="xsd:string">
					<xsd:attribute name="anchor" type="xsd:string" use="required"/>
				</xsd:extension>
			</xsd:simpleContent>
		</xsd:complexType>
	</xsd:element>
	<xsd:element name="return">
		<xsd:complexType>
			<xsd:attribute name="type" type="xsd:string" use="required"/>
		</xsd:complexType>
	</xsd:element>
	<xsd:element name="allowed">
		<xsd:complexType>
			<xsd:sequence>
				<xsd:element ref="value" maxOccurs="unbounded"/>
			</xsd:sequence>
			<xsd:attribute name="kind" type="xsd:string"/>
			<xsd:attribute name="type" type="xsd:string"/>
		</xsd:complexType>
	</xsd:element>
	<xsd:element name="comments">
		<xsd:complexType mixed="true">
			<xsd:sequence>
				<xsd:element ref="link" minOccurs="0"/>
			</xsd:sequence>
		</xsd:complexType>
	</xsd:element>
	<xsd:element name="range">
		<xsd:complexType>
			<xsd:attribute name="min" type="xsd:string" use="required"/>
			<xsd:attribute name="max" type="xsd:string" use="required"/>
		</xsd:complexType>
	</xsd:element>
	<xsd:element name="output">
		<xsd:complexType>
			<xsd:sequence>
				<xsd:element ref="param" maxOccurs="unbounded"/>
			</xsd:sequence>
		</xsd:complexType>
	</xsd:element>
	<xsd:element name="sub" type="xsd:string"/>
	<xsd:element name="sup" type="xsd:string"/>
	<xsd:element name="needs" type="xsd:string"/>
	<xsd:element name="comment">
		<xsd:complexType>
			<xsd:sequence>
				<xsd:element ref="method"/>
			</xsd:sequence>
		</xsd:complexType>
	</xsd:element>
	<xsd:element name="task">
		<xsd:complexType mixed="true">
			<xsd:sequence>
				<xsd:element ref="shortdescription" maxOccurs="unbounded"/>
				<xsd:element ref="input"/>
				<xsd:element ref="output" minOccurs="0"/>
				<xsd:element ref="returns" minOccurs="0"/>
				<xsd:element ref="description" minOccurs="0"/>
				<xsd:element ref="example"/>
			</xsd:sequence>
			<xsd:attribute name="type" type="xsd:string" use="required"/>
			<xsd:attribute name="name" type="xsd:string" use="required"/>
			<xsd:attribute name="category" type="xsd:string" use="required"/>
			<xsd:attribute name="visibility" type="xsd:string"/>
			<xsd:attribute name="async" type="xsd:string"/>
			<xsd:attribute name="startup" type="xsd:string"/>
		</xsd:complexType>
	</xsd:element>
	<xsd:element name="constraints">
		<xsd:complexType>
			<xsd:sequence>
				<xsd:element ref="when" minOccurs="0" maxOccurs="unbounded"/>
			</xsd:sequence>
		</xsd:complexType>
	</xsd:element>
	<xsd:element name="when">
		<xsd:complexType>
			<xsd:sequence>
				<xsd:element ref="notequals" minOccurs="0"/>
				<xsd:element ref="equals" minOccurs="0" maxOccurs="unbounded"/>
			</xsd:sequence>
			<xsd:attribute name="param" type="xsd:string" use="required"/>
		</xsd:complexType>
	</xsd:element>
	<xsd:element name="equals">
		<xsd:complexType>
			<xsd:sequence>
				<xsd:element ref="description" minOccurs="0"/>
				<xsd:element ref="value" minOccurs="0"/>
				<xsd:element ref="default" minOccurs="0" maxOccurs="unbounded"/>
			</xsd:sequence>
			<xsd:attribute name="type" type="xsd:string"/>
			<xsd:attribute name="value" type="xsd:string" use="required"/>
		</xsd:complexType>
	</xsd:element>
	<xsd:element name="default">
		<xsd:complexType>
			<xsd:sequence>
				<xsd:element ref="description" minOccurs="0"/>
				<xsd:element ref="value"/>
			</xsd:sequence>
			<xsd:attribute name="param" type="xsd:string" use="required"/>
			<xsd:attribute name="type" type="xsd:string"/>
		</xsd:complexType>
	</xsd:element>
	<xsd:element name="notequals">
		<xsd:complexType>
			<xsd:sequence>
				<xsd:element ref="default" maxOccurs="unbounded"/>
			</xsd:sequence>
			<xsd:attribute name="type" type="xsd:string"/>
			<xsd:attribute name="value" type="xsd:string" use="required"/>
		</xsd:complexType>
	</xsd:element>
	<xsd:element name="em" type="xsd:string"/>
</xsd:schema>

=== dic-case-studies/casa6/gcwrap/tasks/importnro.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet type="text/xsl" ?>
<casaxml xmlns="http://casa.nrao.edu/schema/psetTypes.html"
xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
xsi:schemaLocation="http://casa.nrao.edu/schema/casa.xsd
file:///opt/casa/code/xmlcasa/xml/casa.xsd">


<task type="function" name="importnro" category="single dish, import/export" >

  <shortdescription>Convert NOSTAR data into a CASA visibility file (MS)</shortdescription>

  <input>

    <param type="string" name="infile" mustexist="true">
          <description>Name of input NOSTAR data</description>
          <value></value>
    </param>

    <param type="string" name="outputvis" kind="ms">
          <description>Root name of the ms to be created. Note the .ms is NOT added </description>
          <value></value>
    </param>

    <param type="bool" name="overwrite">
	    <description>Over write an existing MS(s)</description>
	    <value>False</value>
    </param>

    <param type="bool" name="parallel">
	    <description>Turn on parallel execution</description>
	    <value>False</value>
    </param>

    </input>

  <returns type="bool"/>

  <example>
Keyword arguments:
asdm -- Name of input NOSTAR data
        default: none; example: asdm='mydata.Y'

outputvis -- Root ms name. Note that a prefix (.ms) is NOT appended to this name.
             default: none; example outputvis='myms.ms'

overwrite -- overwrite an existing MS
             default: False (do not overwrite)

parallel  -- Turn on parallel execution
             default: False (serial execution)
  </example>

</task>

</casaxml>

=== dic-case-studies/casa6/casatasks/xml/importvla.xml
<casaxml xsi:schemaLocation="http://casa.nrao.edu/schema/casa.xsd     file:///opt/casa/code/xmlcasa/xml/casa.xsd" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns="http://casa.nrao.edu/schema/psetTypes.html">

    <task category="import/export" name="importvla" type="function">
importvla(archivefiles=None,vis=None,
              bandname=None,frequencytol=None,
              project=None,
              starttime=None,stoptime=None,
              applytsys=None,
              autocorr=None,antnamescheme=None):
  <shortdescription>Import VLA archive file(s) to a measurement set</shortdescription>
<description>
Imports an arbitrary number of VLA archive-format data sets into a
casa measurement set.  If more than one band is present, they will be
put in the same measurement set but in a separate spectral window.
The task will handle old style and new style VLA (after July 2007)
archive data and apply the tsys to the data and to the weights.
</description>
   <input>
       <param mustexist="true" name="archivefiles" type="pathVec">
<shortdescription>Name of input VLA archive file(s)</shortdescription>
<description>Name of input VLA archive file(s)
                     Default: none.  Must be supplied

                        Examples: 
                        archivefiles = 'AP314_A959519.xp1'
                        archivefiles=['AP314_A950519.xp1',
                        'AP314_A950519.xp2']
</description>
           <value/>
       </param>

       <param name="vis" type="string">
<shortdescription>Name of output visibility file</shortdescription>
<description>Name of output visibility file
                     Default: none.  Must be supplied

                        Example: vis='NGC7538.ms'

                     NOTE: Will not over-write existing ms of same
                     name. A backup flag-file version 'Original' will
                     be made in vis.flagversions.  See help
                     flagmanager.
 </description>
           <value/>
       </param>

       <param name="bandname" type="string">
<shortdescription>VLA frequency band name:\'\'=&gt;obtain all bands in the archive file</shortdescription>
<description>VLA frequency band name:
                     Default: '' (obtain all bands in the archive
                     file)
                     Options: '4'=48-96 MHz,'P'=298-345
                     MHz,'L'=1.15-1.75 GHz, 'C'=4.2-5.1
                     GHz,'X'=6.8-9.6 GHz,'U'=13.5-16.3 GHz,
                     'K'=20.8-25.8 GHz,'Q'=38-51 GHz

                        Example: bandname='K'
</description>
           <value/>
           <allowed kind="enum">
               <value>4</value>
               <value>P</value>
               <value>L</value>
               <value>S</value>
               <value>C</value>
               <value>X</value>
               <value>U</value>
               <value>K</value>
               <value>Ka</value>
               <value>Q</value>
               <value/>
           </allowed>
       </param>

       <param name="frequencytol" type="any">
<shortdescription>Frequency shift to define a unique spectra window (Hz)</shortdescription>
<description>Tolerance in frequency shift in making spectral windows
                     Default: = 150000.0Hz'

                        Example: frequencytol = 1500000.0 (units = Hz)

                     For Doppler shifted data, less than 10000 Hz may
                     may produce too many unnecessary spectral
                     windows.
</description>
           <value type="string">150000.0Hz</value>
       </param>

       <param name="project" type="string">
<shortdescription>Project name: \'\' =&gt; all projects in files</shortdescription>
<description>Project name to import from archive files
                     Default: '' (all projects in file)

                        Example: project='AL519'             
                        Project = 'al519' or AL519 will work. 

                     WARNING: Do not include leading zeros; project =
                     'AL0519' will not work.
</description>
           <value/>
       </param>

       <param name="starttime" type="string">
<shortdescription>Start time to search for data</shortdescription>
<description>Time after which data will be considered for importing
                     Default: '' (all)

                     syntax: starttime = '2003/1/31/05:05:23'. Date
                     must be included!
</description>
           <value/>
       </param>

       <param name="stoptime" type="string">
<shortdescription>End time to search for data</shortdescription>
<description>Time before which data will be considered for
importing
                     Default: '' (all)

                     syntax: starttime = '2003/1/31/08:05:23'. Date
                     must be included!
</description>
           <value/>
       </param>

       <param name="applytsys" type="bool">
<shortdescription>Apply nominal sensitivity scaling to data and weights</shortdescription>
<description>Apply data scaling and weight scaling by nominal
sensitivity (~Tsys)
                     Default: True (strongly recommended)
                     Options: True|False
</description>
           <value>True</value>
       </param>

       <param name="autocorr" type="bool">
<shortdescription>Import autocorrelations to MS, if set to True</shortdescription>
<description>Import autocorrelations to MS
                     Default: False (no autocorrelations)
                     Options: False|True
</description>
           <value>False</value>
       </param>


       <param name="antnamescheme" type="string">
<shortdescription>\'old\' or \'new\'; \'VA04\' or \'04\' for VLA ant 4</shortdescription>
<description>'old' or 'new' antenna names.
                     Default: 'new'
                     Options: new|old

                     * 'new' gives antnenna names 'VA04' or 'EA13 for
                       VLA telescopse 04 and 13 (EVLA)
                     * 'old' gives names '04' or '13'
</description>
           <value>new</value>
           <allowed kind="enum">
               <value>old</value>
               <value>new</value>
           </allowed>
       </param>

       <param name="keepblanks" type="bool">
<shortdescription>Fill scans with blank (empty) source names (e.g. tipping scans)</shortdescription>
<description>Should sources with blank names be filled into the data
base?
                     Default: False (do not fill)
                     Options: False|True

                     These scans are tipping scans (as of June 1,
                     2009) and should not be filled in the visibility
                     data set.
</description>
           <value>False</value>
       </param>

       <param name="evlabands" type="bool">
<shortdescription>Use updated eVLA frequencies and bandwidths for bands and wavelengths</shortdescription>
<description>Use the EVLA's center frequency and bandwidths for
frequencies specified via wavelength or band.
                     Default: False
                     Options: False|True
</description>
           <value>False</value>
       </param>
   </input>
   <example>
FOR MORE INFORMATION, SEE THE TASK PAGES OF IMPORTVLA IN CASA DOCS:
https://casa.nrao.edu/casadocs/
   </example>
<returns>void</returns></task>
</casaxml>

=== dic-case-studies/casa6/casatasks/xml/listpartition.xml
<casaxml xsi:schemaLocation="http://casa.nrao.edu/schema/casa.xsd       file:///opt/casa/code/xmlcasa/xml/casa.xsd" xmlns="http://casa.nrao.edu/schema/psetTypes.html" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">

<task type="function" name="listpartition" category="information">
       <shortdescription>List the summary of a multi-MS data set in the logger or in a file</shortdescription>
       <description>
       Lists the following properties of a multi-measurement set:
       sub-MS name, scan list, spw list, list of number of channels per spw, 
       number of rows for all scans.
       </description>
       <input>
              <param type="path" name="vis" mustexist="true"><shortdescription>Name of Multi-MS or normal MS.</shortdescription><description>Name of Multi-MS or normal MS.</description>
                     
                     <value/>
              </param>

        <param type="bool" name="createdict"><shortdescription>Create and return a dictionary with Sub-MS information</shortdescription><description>Create and return a dictionary with Sub-MS information</description>
            
            <value>False</value>
        </param>
              
              <param type="string" name="listfile"><shortdescription>Name of ASCII file to save output: ''==&gt;to terminal</shortdescription><description>Name of ASCII file to save output: ''==&gt;to terminal</description>
                     
                     <value/>
              </param>
            
       </input>
<returns type="void"/>

<example>

       A multi-measurement set (MMS) is an MS that has been split into sub-MSs.
       An MMS contains a reference MS in the top directory and the sub-MSs are 
       located in a directory called SUBMSS inside the MMS directory.
       Example of a MS that was partitioned in the 'scan' axis using the task partition: 

       &gt; ls ngc5921.mms
         ANTENNA           FLAG_CMD     POLARIZATION  SPECTRAL_WINDOW  table.dat
         DATA_DESCRIPTION  HISTORY      PROCESSOR     STATE            table.info
         FEED              OBSERVATION  SORTED_TABLE  SUBMSS           WEATHER
         FIELD             POINTING     SOURCE        SYSCAL

       &gt; ls ngc5921.mms/SUBMSS/
         ngc5921.0000.ms/  ngc5921.0002.ms/  ngc5921.0004.ms/  ngc5921.0006.ms/
         ngc5921.0001.ms/  ngc5921.0003.ms/  ngc5921.0005.ms/
              
       The task lists the following properties of a multi-MS or MS:
       sub-MS name, scan, spw list, list of number of channels per spw, 
       number of rows for each scan and the size in disk. Example of logger output:
       
        Sub-MS          Scan  Spw      Nchan    Nrows   Size  
        ngc5921.0000.ms  1    [0]      [63]     4509    11M
        ngc5921.0001.ms  2    [0]      [63]     1890    6.4M
        ngc5921.0002.ms  3    [0]      [63]     6048    13M
        ngc5921.0003.ms  4    [0]      [63]     756     4.9M
        ngc5921.0004.ms  5    [0]      [63]     1134    6.4M
        ngc5921.0005.ms  6    [0]      [63]     6804    15M
        ngc5921.0006.ms  7    [0]      [63]     1512    6.4M


------- Detailed description of keyword arguments -------
       vis -- Name of multi-MS or normal MS.
              default: ''. 
              example: vis='pScan.mms'

       createdict -- Create and return a dictionary containing scan summaries of each
                     sub-MS. 
              default: False
              
              If set to True, the returned dictionary will contain information from
              ms.getscansummary() and ms.getspectralwindowinfo(), with the addition of an 
              index as the top key and the sub-MS name.
              Example:
              
            {0: {'MS': 'ngc5921.0000.ms',
                 'scanId': {1: {'nchans': array([63], dtype=int32),
                                'nrows': 4509,
                                'spwIds': array([0], dtype=int32)}},
                 'size': '11M'},
             1: {'MS': 'ngc5921.0001.ms',
                 'scanId': {2: {'nchans': array([63], dtype=int32),
                                'nrows': 1890,
                                'spwIds': array([0], dtype=int32)}},
                 'size': '6.4M'}}
                    
       listfile -- Name of ASCII file to save output to. If empty, it will 
                   list on the logger/terminal.
              default: ''
              example: listfile='pscan.txt'

 </example>
 </task>
 </casaxml>

=== dic-case-studies/casa6/casatasks/xml/importuvfits.xml
<casaxml xsi:schemaLocation="http://casa.nrao.edu/schema/casa.xsd       file:///opt/casa/code/xmlcasa/xml/casa.xsd" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns="http://casa.nrao.edu/schema/psetTypes.html">

      <task category="import/export" name="importuvfits" type="function">
    <shortdescription>Convert a UVFITS file to a CASA visibility data set</shortdescription>
    <description>Convert a UVITS file to a CASA visiblity data set.
                Don\'t forget to flag autocorrelations using taskname flagdata, autocorr = true
    </description>
    <input>
        <param name="fitsfile" mustexist="true" type="string"><shortdescription>Name of input UV FITS file</shortdescription><description>Name of input UV FITS file</description>
            
            <value/>
        </param>

        <param name="vis" type="string"><shortdescription>Name of output visibility file (MS)</shortdescription><description>Name of output visibility file (MS)</description>
            
            <value/>
        </param>
        <param name="antnamescheme" type="string"><shortdescription>VLA/EVLA/CARMA only; \'new\' or \'old\'; \'VA04\' or \'04\' for VLA ant 4</shortdescription><description>VLA/EVLA/CARMA only; \'new\' or \'old\'; \'VA04\' or \'04\' for VLA ant 4</description>
                  
          <value>old</value>
          <allowed kind="enum">
          <value>old</value>
          <value>new</value>
          </allowed>
        </param>
    </input>

<example>
        Convert a UVFITS file to a CASA visibility data set:

        Keyword arguments:
        fitsfile -- Name of input UV FITS file
                default = none; example='3C273XC1.fits'
        vis -- Name of output visibility file (MS)
                default = none; example: vis='3C273XC1.ms'
        antnamescheme -- Naming scheme for VLA/JVLA/CARMA antennas
                default = old;
                  old: Antenna name is a number, '04'
                       This option exists for backwards compatibility
                       but can lead to ambiguous results when antenna
                       indices are used for data selection.
                  new: Antenna name is not a number, e.g., 'VA04' or 'EA04'
                       With this scheme, data selection via
                       antenna names and indices is non-ambiguous.

        Note: Don't forget to flag autocorrections using
           taskname flagdata, autocorr = true

 </example>
 </task>
 </casaxml>

=== dic-case-studies/casa6/gcwrap/tasks/listhistory.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet type="text/xsl" ?>
<casaxml xmlns="http://casa.nrao.edu/schema/psetTypes.html"
      xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
      xsi:schemaLocation="http://casa.nrao.edu/schema/casa.xsd
      file:///opt/casa/code/xmlcasa/xml/casa.xsd">

<task type="function" name="listhistory" category="information">
    <shortdescription>List the processing history of a dataset:</shortdescription>
    <description>
        List the processing history of a dataset:
        The list of all task processing steps will be
        given in the logger.
    </description>
    <input>
        <param type="string" name="vis" mustexist="true">
            <description>Name of input visibility file (MS)</description>
            <value></value>
        </param>
    </input>
<returns type="void"/>

<example>

        The list of all task processing steps in a visibility data set
        are listed in the logger.

        Keyword arguments:
        vis -- Name of input visibility file 
                default: none; example: vis='ngc5921.ms'
        async -- Run asynchronously 
                default = False; do not run asychronously
 </example>
 </task>
 </casaxml>
