=== dic-case-studies/casa6/casa5/gcwrap/xml/casa.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xsd:schema elementFormDefault="qualified" 
	targetNamespace="urn:Test.Namespace"
	xmlns:xsd="http://www.w3.org/2001/XMLSchema"
	xmlns="urn:Test.Namespace">
	<xsd:element name="casaxml">
		<xsd:complexType>
			<xsd:sequence>
				<xsd:element ref="task" maxOccurs="unbounded"/>
				<xsd:element ref="tool" maxOccurs="unbounded"/>
			</xsd:sequence>
		</xsd:complexType>
	</xsd:element>
	<xsd:element name="tool">
		<xsd:complexType mixed="true">
			<xsd:sequence>
				<xsd:element ref="keyword" minOccurs="0" maxOccurs="unbounded"/>
				<xsd:element ref="code" minOccurs="0"/>
				<xsd:element ref="shortdescription"/>
				<xsd:element ref="description" minOccurs="0"/>
				<xsd:element ref="example" minOccurs="0"/>
				<xsd:element ref="needs" minOccurs="0"/>
				<xsd:element ref="comment" minOccurs="0"/>
				<xsd:element ref="comments" minOccurs="0"/>
				<xsd:element ref="method" maxOccurs="unbounded"/>
			</xsd:sequence>
			<xsd:attribute name="name" type="xsd:string" use="required"/>
			<xsd:attribute name="module" type="xsd:string" use="required"/>
		</xsd:complexType>
	</xsd:element>
	<xsd:element name="method">
		<xsd:complexType mixed="true">
			<xsd:sequence>
				<xsd:element ref="comments" minOccurs="0"/>
				<xsd:element ref="return" minOccurs="0"/>
				<xsd:element ref="keyword" minOccurs="0" maxOccurs="unbounded"/>
				<xsd:element ref="shortdescription" minOccurs="0"/>
				<xsd:element ref="description" minOccurs="0"/>
				<xsd:element ref="output" minOccurs="0"/>
				<xsd:element ref="input" minOccurs="0"/>
				<xsd:element ref="returns" minOccurs="0"/>
				<xsd:element ref="example" minOccurs="0" maxOccurs="unbounded"/>
			</xsd:sequence>
			<xsd:attribute name="type" type="xsd:string" use="required"/>
			<xsd:attribute name="name" type="xsd:string" use="required"/>
			<xsd:attribute name="direction" type="xsd:string"/>
		</xsd:complexType>
	</xsd:element>
	<xsd:element name="example">
		<xsd:complexType mixed="true">
			<xsd:sequence>
				<xsd:element ref="comments" minOccurs="0"/>
				<xsd:element ref="link" minOccurs="0" maxOccurs="unbounded"/>
			</xsd:sequence>
		</xsd:complexType>
	</xsd:element>
	<xsd:element name="returns">
		<xsd:complexType mixed="true">
			<xsd:sequence>
				<xsd:element ref="any" minOccurs="0"/>
				<xsd:element ref="shortdescription" minOccurs="0"/>
				<xsd:element ref="description" minOccurs="0"/>
			</xsd:sequence>
			<xsd:attribute name="type" type="xsd:string"/>
		</xsd:complexType>
	</xsd:element>
	<xsd:element name="input">
		<xsd:complexType>
			<xsd:sequence>
				<xsd:element ref="value" minOccurs="0"/>
				<xsd:element ref="param" minOccurs="0" maxOccurs="unbounded"/>
			</xsd:sequence>
		</xsd:complexType>
	</xsd:element>
	<xsd:element name="description">
		<xsd:complexType mixed="true">
			<xsd:sequence>
				<xsd:element ref="sup" minOccurs="0" maxOccurs="unbounded"/>
				<xsd:element ref="sub" minOccurs="0" maxOccurs="unbounded"/>
				<xsd:element ref="link" minOccurs="0" maxOccurs="unbounded"/>
			</xsd:sequence>
		</xsd:complexType>
	</xsd:element>
	<xsd:element name="shortdescription">
		<xsd:complexType mixed="true">
			<xsd:sequence>
				<xsd:element ref="link" minOccurs="0" maxOccurs="unbounded"/>
			</xsd:sequence>
		</xsd:complexType>
	</xsd:element>
	<xsd:element name="param">
		<xsd:complexType>
			<xsd:sequence>
				<xsd:element ref="allowed" minOccurs="0"/>
				<xsd:element ref="choice" minOccurs="0" maxOccurs="unbounded"/>
				<xsd:element ref="any" minOccurs="0"/>
				<xsd:element ref="description" minOccurs="0"/>
				<xsd:element ref="range" minOccurs="0"/>
				<xsd:element ref="value" minOccurs="0" maxOccurs="unbounded"/>
			</xsd:sequence>
			<xsd:attribute name="type" type="xsd:string" use="required"/>
			<xsd:attribute name="name" type="xsd:string" use="required"/>
			<xsd:attribute name="direction" type="xsd:string"/>
			<xsd:attribute name="units" type="xsd:string"/>
			<xsd:attribute name="mustexist" type="xsd:string"/>
		</xsd:complexType>
	</xsd:element>
	<xsd:element name="value">
		<xsd:complexType mixed="true">
			<xsd:sequence>
				<xsd:element ref="value" minOccurs="0" maxOccurs="unbounded"/>
			</xsd:sequence>
			<xsd:attribute name="type" type="xsd:string"/>
		</xsd:complexType>
	</xsd:element>
	<xsd:element name="any">
		<xsd:complexType>
			<xsd:attribute name="type" type="xsd:string" use="required"/>
			<xsd:attribute name="limittypes" type="xsd:string"/>
		</xsd:complexType>
	</xsd:element>
	<xsd:element name="code">
		<xsd:complexType>
			<xsd:sequence>
				<xsd:element ref="include"/>
				<xsd:element ref="private"/>
			</xsd:sequence>
		</xsd:complexType>
	</xsd:element>
	<xsd:element name="private">
		<xsd:complexType>
			<xsd:sequence>
				<xsd:element ref="include"/>
			</xsd:sequence>
		</xsd:complexType>
	</xsd:element>
	<xsd:element name="include" type="xsd:string"/>
	<xsd:element name="keyword" type="xsd:string"/>
	<xsd:element name="choice" type="xsd:string"/>
	<xsd:element name="link">
		<xsd:complexType>
			<xsd:simpleContent>
				<xsd:extension base="xsd:string">
					<xsd:attribute name="anchor" type="xsd:string" use="required"/>
				</xsd:extension>
			</xsd:simpleContent>
		</xsd:complexType>
	</xsd:element>
	<xsd:element name="return">
		<xsd:complexType>
			<xsd:attribute name="type" type="xsd:string" use="required"/>
		</xsd:complexType>
	</xsd:element>
	<xsd:element name="allowed">
		<xsd:complexType>
			<xsd:sequence>
				<xsd:element ref="value" maxOccurs="unbounded"/>
			</xsd:sequence>
			<xsd:attribute name="kind" type="xsd:string"/>
			<xsd:attribute name="type" type="xsd:string"/>
		</xsd:complexType>
	</xsd:element>
	<xsd:element name="comments">
		<xsd:complexType mixed="true">
			<xsd:sequence>
				<xsd:element ref="link" minOccurs="0"/>
			</xsd:sequence>
		</xsd:complexType>
	</xsd:element>
	<xsd:element name="range">
		<xsd:complexType>
			<xsd:attribute name="min" type="xsd:string" use="required"/>
			<xsd:attribute name="max" type="xsd:string" use="required"/>
		</xsd:complexType>
	</xsd:element>
	<xsd:element name="output">
		<xsd:complexType>
			<xsd:sequence>
				<xsd:element ref="param" maxOccurs="unbounded"/>
			</xsd:sequence>
		</xsd:complexType>
	</xsd:element>
	<xsd:element name="sub" type="xsd:string"/>
	<xsd:element name="sup" type="xsd:string"/>
	<xsd:element name="needs" type="xsd:string"/>
	<xsd:element name="comment">
		<xsd:complexType>
			<xsd:sequence>
				<xsd:element ref="method"/>
			</xsd:sequence>
		</xsd:complexType>
	</xsd:element>
	<xsd:element name="task">
		<xsd:complexType mixed="true">
			<xsd:sequence>
				<xsd:element ref="shortdescription" maxOccurs="unbounded"/>
				<xsd:element ref="input"/>
				<xsd:element ref="output" minOccurs="0"/>
				<xsd:element ref="returns" minOccurs="0"/>
				<xsd:element ref="description" minOccurs="0"/>
				<xsd:element ref="example"/>
			</xsd:sequence>
			<xsd:attribute name="type" type="xsd:string" use="required"/>
			<xsd:attribute name="name" type="xsd:string" use="required"/>
			<xsd:attribute name="category" type="xsd:string" use="required"/>
			<xsd:attribute name="visibility" type="xsd:string"/>
			<xsd:attribute name="async" type="xsd:string"/>
			<xsd:attribute name="startup" type="xsd:string"/>
		</xsd:complexType>
	</xsd:element>
	<xsd:element name="constraints">
		<xsd:complexType>
			<xsd:sequence>
				<xsd:element ref="when" minOccurs="0" maxOccurs="unbounded"/>
			</xsd:sequence>
		</xsd:complexType>
	</xsd:element>
	<xsd:element name="when">
		<xsd:complexType>
			<xsd:sequence>
				<xsd:element ref="notequals" minOccurs="0"/>
				<xsd:element ref="equals" minOccurs="0" maxOccurs="unbounded"/>
			</xsd:sequence>
			<xsd:attribute name="param" type="xsd:string" use="required"/>
		</xsd:complexType>
	</xsd:element>
	<xsd:element name="equals">
		<xsd:complexType>
			<xsd:sequence>
				<xsd:element ref="description" minOccurs="0"/>
				<xsd:element ref="value" minOccurs="0"/>
				<xsd:element ref="default" minOccurs="0" maxOccurs="unbounded"/>
			</xsd:sequence>
			<xsd:attribute name="type" type="xsd:string"/>
			<xsd:attribute name="value" type="xsd:string" use="required"/>
		</xsd:complexType>
	</xsd:element>
	<xsd:element name="default">
		<xsd:complexType>
			<xsd:sequence>
				<xsd:element ref="description" minOccurs="0"/>
				<xsd:element ref="value"/>
			</xsd:sequence>
			<xsd:attribute name="param" type="xsd:string" use="required"/>
			<xsd:attribute name="type" type="xsd:string"/>
		</xsd:complexType>
	</xsd:element>
	<xsd:element name="notequals">
		<xsd:complexType>
			<xsd:sequence>
				<xsd:element ref="default" maxOccurs="unbounded"/>
			</xsd:sequence>
			<xsd:attribute name="type" type="xsd:string"/>
			<xsd:attribute name="value" type="xsd:string" use="required"/>
		</xsd:complexType>
	</xsd:element>
	<xsd:element name="em" type="xsd:string"/>
</xsd:schema>

=== dic-case-studies/casa6/gcwrap/tasks/msuvbin.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet type="text/xsl" ?>
<casaxml xmlns="http://casa.nrao.edu/schema/psetTypes.html"
      xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
      xsi:schemaLocation="http://casa.nrao.edu/schema/casa.xsd
      file:///opt/casa/code/xmlcasa/xml/casa.xsd">

<task type="function" name="msuvbin" category="calibration" visibility="experimental">
  <shortdescription>grid the visibility data onto a defined uniform grid (in the form of an ms); multiple MS\'s can be done onto the same grid</shortdescription>
  <description>
          msuvbin is a uv gridding task. The use is for large volumes
          of data (from multiple epochs) that needs to be imaged into
          one image.  One way of proceeding is to image the epochs and
          average them after wards. Rather than doing this averaging
          the visibilities on a common uv grid has several convenience
          advantages like easily doing the proper weighted averaging and imaging.
          If an output grid already exists and a second ms is gridded on the grid
          then the output grid parameters is ignored but the existant grid is used.

  </description>
  <input>
    <param type="string" name="vis" mustexist="true">
      <description>Name of input visibility file (MS)</description>
      <value></value>
    </param>

    <param type="string" name="field">
      <description>Field selection of input ms</description>
      <value></value>
    </param>

    <param type="string" name="spw">
      <description>Spw selection</description>
      <value></value>
    </param>

    <param type="string" name="taql">
      <description>TaQl string for data selection</description>
      <value></value>
    </param>

    <param type="string" name="outvis">
      <description>name of output uvgrid</description>
      <value></value>
    </param>
    <param type="string" name="phasecenter">
      <description>phase center of uv grid</description>
      <value></value>
    </param>
    <param type="int" name="nx">
      <description>Number of pixels of grid along the x-axis</description>
      <value>1000</value>
    </param>
    <param type="int" name="ny">
      <description>Number of pixels of grid along the y-axis</description>
      <value>1000</value>
    </param>
    <param type="string" name="cell">
      <description>pixel cell size defined in sky dimension</description>
      <value>1arcsec</value>
    </param>
    <param type="int" name="ncorr">
      <description>number of correlations to store in grid</description>
      <value>1</value>
      <allowed kind="enum">
        <value>1</value>
        <value>2</value>
        <value>4</value>
      </allowed>
    </param>
    <param type="int" name="nchan">
      <description>Number of spectral channels in grid</description>
      <value>1</value>
    </param>
    <param type="string" name="fstart">
      <description>Frequency of first spectral channel</description>
      <value>1GHz</value>
    </param>
    <param type="string" name="fstep">
      <description>spectral channel width</description>
      <value>1kHz</value>
    </param>
    <param type="bool" name="wproject">
      <description>Do wprojection correction while gridding</description>
      <value>False</value>
    </param>
    <param type="double" name="memfrac">
      <description>Limit how much of memory to use</description>
      <value>0.5</value>
      <allowed kind="range">
        <value range="min">0.01</value>
        <value range="max">0.99</value>
      </allowed>
    </param>



  </input>
<returns type="void"/>

<example>




       Keyword arguments:
       vis -- Name of input visibility file
              default: none; example: vis='ngc5921.ms'
       field -- Field name list
               default: '' ==> all
               field = '1328+307'  specifies source '1328+307'
               field = '4' specified field with index 4
       spw -- Spw selection
               default: spw = '' (all spw)
               spw='2'
       taql  --TaQl expression for data selection (see http://www.astron.nl/casacore/trunk/casacore/doc/notes/199.html)
               default taql=''
               Example select all data where U &gt; 1 m in the ms
               taql='UVW[0] &gt; 1'
       outvis -- name of output grid
               default: ''  The user has to give something here
       phasecenter -- phasecenter of the grid
               default= ''
                phasecenter='J2000 18h03m04 -20d00m45.1'
      nx  -- number of pixels along the x axis of the grid
               default: 1000
               nx=1200
      ny  -- number of pixels along the y axis of the grid
               default: 1000
               ny=1200
       cell -- cellsize of the grid (given in sky units)
               default: '1arcsec'
               cell='0.1arcsec'
        ncorr -- number of correlation/polarization plane in uv grid (allowed 1, 2, 4)
               default: 1
               ncorr=4
        nchan -- number of spectral channel
               default: 1
               nchan=2000
        fstart -- frequency of the first channel
               default: '1GHz';  User has to give something useful here
        fstep -- spectral channel width
               default: '1kHz'
        wproject -- do wprojection correction while gridding
                default: False
                wproject=True
        memfrac -- control how much of computer's memory is available for  gridding
                default=0.5
                memfrac=0.9

 </example>
 </task>
 </casaxml>

=== dic-case-studies/casa6/gcwrap/tasks/imcontsub.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet type="text/xsl" ?>

<casaxml xmlns="http://casa.nrao.edu/schema/psetTypes.html"
xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
xsi:schemaLocation="http://casa.nrao.edu/schema/casa.xsd
file:///opt/casa/code/xmlcasa/xml/casa.xsd">


<!-- This is the image continuum subtraction task                           -->
<!-- step 1: construct region with the region manger tool, rg               -->
<!-- step 2: do the subtraction, with ia.continuumsub (image analysis tool) -->
<!--                                                                        -->
<!-- TODO: Expand region selection                                          -->

<task type="function" name="imcontsub" category="analysis, imaging">
<shortdescription>Estimates and subtracts continuum emission from an image cube</shortdescription>
<description>
Estimates and subtracts continuum emission from an image cube

For each direction pixel (x, y) column in imagename (or a subset
selected by region and/or box), this estimates the continuum by
fitting a polynomial to one or more subsets of the channels.  The
continuum estimate is saved in contfile, and subtracted from imagename
(or its subset) to make a spectral line estimate, which is saved in
linefile.
</description>
<input>
    <param type="string" name="imagename" mustexist="true" >
<shortdescription>Name of the input spectral line image</shortdescription>
<description>Input image cube.
                     Default: none

                        Example: imagename='ngc5921_task.im'
</description>
        <value></value>
        <example>inputfile=ngc5921_task.image</example>
    </param>

    <param type="string" name="linefile" >
<shortdescription>Output continuum-subtracted image file name</shortdescription>
<description>Name of continuum-subtracted output spectral line cube
                     Default: none

                        Example: outline='ngc5921_line.im'
</description>
        <value></value>
        <example>outline=ngc5921_line.image</example>
    </param>

    <param type="string" name="contfile" >
<shortdescription>Output continuum image file name</shortdescription>
<description>Name of output continuum cube
                     Default: none

                        Example: contfile='ngc5921_cont.im'
</description>
        <value></value>
        <example>outcont=ngc5921_cont.image</example>
    </param>

    <param type="int" name="fitorder" >
<shortdescription>Polynomial order for the continuum estimation</shortdescription>
<description>Polynomial order for the continuum estimation
                     Default: 0

                        Example: fitorder=2
</description>
        <value>0</value>
    <allowed kind="range"><value range="min">0</value></allowed> 
        <example>fitorder=2</example>
    </param>

    <param type="string" name="region">
<shortdescription>Region selection.</shortdescription>
<description>Region selection. 
                     Default: '' (use the full image)
</description>
        <value/>
    </param>
    <param type="any" name="box">
<shortdescription>Rectangular region to select in direction plane. Default is to use the entire direction plane.</shortdescription>
<description>Rectangular region to select in direction plane.
                     Default: '' (use the entire direction plane)
</description>
        <any type="variant" limittypes="string intArray stringArray"/>
        <value type="string"/>
    </param>
    <param type="string" name="chans" >
<shortdescription>Channels to use.</shortdescription>
<description>Channels to use. 
                     Default: '' (use all channels)
</description>
        <value/>
    </param>
    <param type="string" name="stokes">
<shortdescription>Stokes planes to use.</shortdescription>
<description>Stokes planes to use.
                     Default: '' (use all Stokes planes)
</description>
        <value/>
    </param>

    <constraints>
    </constraints>
</input>
<returns type="void"/>



<example>
FOR MORE INFORMATION, SEE THE TASK PAGES OF IMCONTSUB IN CASA DOCS:
https://casa.nrao.edu/casadocs/
</example>
</task>
</casaxml>

=== dic-case-studies/casa6/casatools/xml/miriadfiller.xml
<casaxml xsi:schemaLocation="http://casa.nrao.edu/schema/casa.xsd file:///opt/casa/code/tools/xml/casa.xsd" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns="http://casa.nrao.edu/schema/psetTypes.html">




<tool module="miriad" name="miriadfiller">

<shortdescription>Tool for the importmiriad task</shortdescription>

<description/>


<method name="miriadfiller" type="constructor">

  <shortdescription>Construct a miriadfiller tool</shortdescription>

  <description/>

  <input/>

  <returns type="miriadfiller"/>

  <example/>

</method>

<method name="fill" type="function">

  <shortdescription>Perform fill operation</shortdescription>

  <description/>

  <input>

    <param name="vis" type="string">
    <description>Name of output visibility file (MS)</description>
    </param>

    <param name="inputfile" type="string">
    <description>Name of miriad input file</description>
    </param>

    <param name="tsys" type="bool">
    <description>Fill weights from Tsys in data?</description>
    <value>false</value>
    </param>

    <param name="spw" type="intVec">
    <description>Spectral windows to load, default=all</description>
    <value><value>-1</value></value>
    </param>

    <param name="vel" type="string">
    <description>Velocity system to use (LSRK, LSRD, TOPO)? Default is telescope dependent</description>
    <value/>
    </param>

    <param name="linecal" type="bool">
    <description>(CARMA) Apply line calibration</description>
    <value>false</value>
    </param>

    <param name="wide" type="intVec">
    <description>(CARMA) Select wide window averages</description>
    <value/>
    </param>

    <param name="debug" type="int">
    <description>Display increasingly verbose debug messages</description>
    <value>0</value>
    </param>

  </input>

  <returns type="void"/>

  <example>
    mf=miriadfiller()
    mf.fill(vis='mir.ms',inputfile='mydata.uv',tsys=True,spw='0,1')
  </example>

</method>

</tool>

</casaxml>

=== dic-case-studies/casa6/gcwrap/tasks/polfromgain.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet type="text/xsl" ?>
<casaxml xmlns="http://casa.nrao.edu/schema/psetTypes.html"
      xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
      xsi:schemaLocation="http://casa.nrao.edu/schema/casa.xsd
      file:///opt/casa/code/xmlcasa/xml/casa.xsd">

<task type="function" name="polfromgain" category="calibration">
        <shortdescription>Derive linear polarization from gain ratio</shortdescription>
        <description>
          TBD
        </description>
        <input>
                <param type="string" name="vis" mustexist="true">
                        <description>Name of input visibility file (MS)</description>
                        <value></value>
                </param>

                <param type="string" name="tablein" mustexist="true">
                        <description>Input calibration table</description>
                        <value></value>
                </param>

                <param type="string" name="caltable">
                        <description>Output calibration table (forces polarization correction if specified)</description>
                        <value></value>
                </param>

                <param type="double" name="paoffset">
                        <description>Manual position angle offset</description>
                        <value>0.0</value>
                </param>

        </input>
<returns type="void"/>

<example>


        TBD...

        Keyword arguments:
        vis -- Name of input visibility file
                default: none; 
        tablein -- Input calibration table (G or T)
                default: none; 
        caltable -- Output calibration table
                default: ''  (no new table)
                if specified, new caltable with polarization removed is generated
        paoffset -- Manual position angle offset
              default: 0.0  (no extra offset)
              example: paoffset=10.0  (10 degree offset)

 </example>
 </task>
 </casaxml>

=== dic-case-studies/casa6/casatasks/xml/sdpolaverage.xml
<casaxml xsi:schemaLocation="http://casa.nrao.edu/schema/casa.xsd file:///opt/casa/code/xmlcasa/xml/casa.xsd" xmlns="http://casa.nrao.edu/schema/psetTypes.html" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">

<task type="function" name="sdpolaverage" category="single dish">
     <shortdescription>Average SD spectra over polarisation</shortdescription>

<description>
    
    The task sdpolaverage exports data averaged over different polarisations.
    Scope of this task is to obtain Stokes I from orthogonal autocorrelation 
    pairs (XXYY/LLRR). Available options include:

    * '' (blank string as the default: polarisation averaging turned off)
    * stokes
    * geometric

</description>

<input>
    <param type="path" name="infile" mustexist="true"><shortdescription>name of input SD dataset</shortdescription><description>name of input SD dataset</description>
        
        <value/>
    </param>
    
    <param type="string" name="datacolumn" ignorecase="true"><shortdescription>name of data column to be used [&quot;data&quot;, &quot;float_data&quot;, or &quot;corrected_data&quot;]</shortdescription><description>name of data column to be used [&quot;data&quot;, &quot;float_data&quot;, or &quot;corrected_data&quot;]</description>
        
        <value>data</value>
    </param>

    <param type="string" name="antenna"><shortdescription>select data by antenna name or ID, e.g. &quot;PM03&quot;</shortdescription><description>select data by antenna name or ID, e.g. &quot;PM03&quot;</description>
        
        <value/>
    </param>
    
    <param type="string" name="field"><shortdescription>select data by field IDs and names, e.g. &quot;3C2*&quot; (&quot;&quot;=all)</shortdescription><description>select data by field IDs and names, e.g. &quot;3C2*&quot; (&quot;&quot;=all)</description>
        
        <value/>
    </param>

    <param type="string" name="spw"><shortdescription>select data by IF IDs (spectral windows), e.g. &quot;3,5,7&quot; (&quot;&quot;=all)</shortdescription><description>select data by IF IDs (spectral windows), e.g. &quot;3,5,7&quot; (&quot;&quot;=all)</description>
        
        <value/>
    </param>
    
    <param type="string" name="timerange"><shortdescription>select data by time range, e.g. &quot;09:14:0~09:54:0&quot; (&quot;&quot;=all) (see examples in help)</shortdescription><description>select data by time range, e.g. &quot;09:14:0~09:54:0&quot; (&quot;&quot;=all) (see examples in help)</description>
        
        <value/>
    </param>
    
    <param type="string" name="scan"><shortdescription>select data by scan numbers, e.g. &quot;21~23&quot; (&quot;&quot;=all)</shortdescription><description>select data by scan numbers, e.g. &quot;21~23&quot; (&quot;&quot;=all)</description>
        
        <value/>
    </param>

    <param type="string" name="intent"><shortdescription>select data by observational intent, e.g. &quot;*ON_SOURCE*&quot; (&quot;&quot;=all)</shortdescription><description>select data by observational intent, e.g. &quot;*ON_SOURCE*&quot; (&quot;&quot;=all)</description>
        
        <value/>
    </param>

    <param type="string" name="polaverage"><shortdescription>polarization averaging mode (&quot;&quot;, &quot;stokes&quot; or &quot;geometric&quot;).</shortdescription><description>polarization averaging mode (&quot;&quot;, &quot;stokes&quot; or &quot;geometric&quot;).</description>
        
        <allowed kind="enum">
            <value/>
            <value>stokes</value>
            <value>geometric</value>
        </allowed>
        <value/>
    </param>

    <param type="string" name="outfile"><shortdescription>name of output file</shortdescription><description>name of output file</description>
        
        <value/>
    </param>
</input>

<example>  
-----------------
Keyword arguments
-----------------
infile -- name of input SD dataset
datacolumn -- name of data column to be used
        options: 'data', 'float_data', or 'corrected_data'
        default: 'data'
antenna -- select data by antenna name or ID
        default: '' (use all antennas)
        example: 'PM03'
field -- select data by field IDs and names
        default: '' (use all fields)
        example: field='3C2*' (all names starting with 3C2)
                 field='0,4,5~7' (field IDs 0,4,5,6,7)
                 field='0,3C273' (field ID 0 or field named 3C273)
        this selection is in addition to the other selections to data
spw -- select data by IF IDs (spectral windows)/channels
        default: '' (use all IFs and channels)
        example: spw='0~2,4'; spectral windows 0,1,2,4 (all channels)
                 spw='&lt;2';  spectral windows less than 2 (i.e. 0,1)
                 spw='0:5~61'; spw 0, channels 5 to 61
                 spw='0,10,3:3~45'; spw 0,10 all channels, spw 3 - chans 3 to 45.
                 spw='0~2:2~6'; spw 0,1,2 with channels 2 through 6 in each.
                 spw = '*:3~64'  channels 3 through 64 for all sp id's
                 spw = ' :3~64' will NOT work.

                 NOTE: sdpolaverage does not support multiple channel ranges 
                       per spectral window (';') just like mstransform doesn't.
        this selection is in addition to the other selections to data
timerange -- select data by time range
        default: '' (use all)
        example: timerange = 'YYYY/MM/DD/hh:mm:ss~YYYY/MM/DD/hh:mm:ss'
                 Note: YYYY/MM/DD can be dropped as needed:
                 timerange='09:14:00~09:54:00' # this time range
                 timerange='09:44:00' # data within one integration of time
                 timerange='&gt;10:24:00' # data after this time
                 timerange='09:44:00+00:13:00' #data 13 minutes after time
        this selection is in addition to the other selections to data
scan -- select data by scan numbers
        default: '' (use all scans)
        example: scan='21~23' (scan IDs 21,22,23)
        this selection is in addition to the other selections to data
intent -- select data by observational intent, also referred to as 'scan intent'
        default: '' (use all scan intents)
        example: intent='*ON_SOURCE*' (any valid scan-intent expression accepted by the MSSelection module can be specified)
        this selection is in addition to the other selections to data
polaverage -- polarization averaging mode
        default: '' (no averaging over polarization)
        options: '', 'stokes', 'geometric'
outfile -- name of output file


-------
POLARIZATION AVERAGE
-------
Two modes of polarization averaging are available. The default is 
'stokes' which is an average based on a formulation of Stokes 
parameter. In this mode, averaged data is calculated by 
(XX + YY) / 2 or (RR + LL) / 2. Other option is 'geometric', which 
is a conventional way of averaging in the field of single-dish 
data reduction. The averaged data is given by weighted average 
of XX and YY, or RR and LL. 

</example> 
<returns>void</returns></task>
</casaxml>
