=== dic-case-studies/casa6/casa5/gcwrap/xml/casa.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xsd:schema elementFormDefault="qualified" 
	targetNamespace="urn:Test.Namespace"
	xmlns:xsd="http://www.w3.org/2001/XMLSchema"
	xmlns="urn:Test.Namespace">
	<xsd:element name="casaxml">
		<xsd:complexType>
			<xsd:sequence>
				<xsd:element ref="task" maxOccurs="unbounded"/>
				<xsd:element ref="tool" maxOccurs="unbounded"/>
			</xsd:sequence>
		</xsd:complexType>
	</xsd:element>
	<xsd:element name="tool">
		<xsd:complexType mixed="true">
			<xsd:sequence>
				<xsd:element ref="keyword" minOccurs="0" maxOccurs="unbounded"/>
				<xsd:element ref="code" minOccurs="0"/>
				<xsd:element ref="shortdescription"/>
				<xsd:element ref="description" minOccurs="0"/>
				<xsd:element ref="example" minOccurs="0"/>
				<xsd:element ref="needs" minOccurs="0"/>
				<xsd:element ref="comment" minOccurs="0"/>
				<xsd:element ref="comments" minOccurs="0"/>
				<xsd:element ref="method" maxOccurs="unbounded"/>
			</xsd:sequence>
			<xsd:attribute name="name" type="xsd:string" use="required"/>
			<xsd:attribute name="module" type="xsd:string" use="required"/>
		</xsd:complexType>
	</xsd:element>
	<xsd:element name="method">
		<xsd:complexType mixed="true">
			<xsd:sequence>
				<xsd:element ref="comments" minOccurs="0"/>
				<xsd:element ref="return" minOccurs="0"/>
				<xsd:element ref="keyword" minOccurs="0" maxOccurs="unbounded"/>
				<xsd:element ref="shortdescription" minOccurs="0"/>
				<xsd:element ref="description" minOccurs="0"/>
				<xsd:element ref="output" minOccurs="0"/>
				<xsd:element ref="input" minOccurs="0"/>
				<xsd:element ref="returns" minOccurs="0"/>
				<xsd:element ref="example" minOccurs="0" maxOccurs="unbounded"/>
			</xsd:sequence>
			<xsd:attribute name="type" type="xsd:string" use="required"/>
			<xsd:attribute name="name" type="xsd:string" use="required"/>
			<xsd:attribute name="direction" type="xsd:string"/>
		</xsd:complexType>
	</xsd:element>
	<xsd:element name="example">
		<xsd:complexType mixed="true">
			<xsd:sequence>
				<xsd:element ref="comments" minOccurs="0"/>
				<xsd:element ref="link" minOccurs="0" maxOccurs="unbounded"/>
			</xsd:sequence>
		</xsd:complexType>
	</xsd:element>
	<xsd:element name="returns">
		<xsd:complexType mixed="true">
			<xsd:sequence>
				<xsd:element ref="any" minOccurs="0"/>
				<xsd:element ref="shortdescription" minOccurs="0"/>
				<xsd:element ref="description" minOccurs="0"/>
			</xsd:sequence>
			<xsd:attribute name="type" type="xsd:string"/>
		</xsd:complexType>
	</xsd:element>
	<xsd:element name="input">
		<xsd:complexType>
			<xsd:sequence>
				<xsd:element ref="value" minOccurs="0"/>
				<xsd:element ref="param" minOccurs="0" maxOccurs="unbounded"/>
			</xsd:sequence>
		</xsd:complexType>
	</xsd:element>
	<xsd:element name="description">
		<xsd:complexType mixed="true">
			<xsd:sequence>
				<xsd:element ref="sup" minOccurs="0" maxOccurs="unbounded"/>
				<xsd:element ref="sub" minOccurs="0" maxOccurs="unbounded"/>
				<xsd:element ref="link" minOccurs="0" maxOccurs="unbounded"/>
			</xsd:sequence>
		</xsd:complexType>
	</xsd:element>
	<xsd:element name="shortdescription">
		<xsd:complexType mixed="true">
			<xsd:sequence>
				<xsd:element ref="link" minOccurs="0" maxOccurs="unbounded"/>
			</xsd:sequence>
		</xsd:complexType>
	</xsd:element>
	<xsd:element name="param">
		<xsd:complexType>
			<xsd:sequence>
				<xsd:element ref="allowed" minOccurs="0"/>
				<xsd:element ref="choice" minOccurs="0" maxOccurs="unbounded"/>
				<xsd:element ref="any" minOccurs="0"/>
				<xsd:element ref="description" minOccurs="0"/>
				<xsd:element ref="range" minOccurs="0"/>
				<xsd:element ref="value" minOccurs="0" maxOccurs="unbounded"/>
			</xsd:sequence>
			<xsd:attribute name="type" type="xsd:string" use="required"/>
			<xsd:attribute name="name" type="xsd:string" use="required"/>
			<xsd:attribute name="direction" type="xsd:string"/>
			<xsd:attribute name="units" type="xsd:string"/>
			<xsd:attribute name="mustexist" type="xsd:string"/>
		</xsd:complexType>
	</xsd:element>
	<xsd:element name="value">
		<xsd:complexType mixed="true">
			<xsd:sequence>
				<xsd:element ref="value" minOccurs="0" maxOccurs="unbounded"/>
			</xsd:sequence>
			<xsd:attribute name="type" type="xsd:string"/>
		</xsd:complexType>
	</xsd:element>
	<xsd:element name="any">
		<xsd:complexType>
			<xsd:attribute name="type" type="xsd:string" use="required"/>
			<xsd:attribute name="limittypes" type="xsd:string"/>
		</xsd:complexType>
	</xsd:element>
	<xsd:element name="code">
		<xsd:complexType>
			<xsd:sequence>
				<xsd:element ref="include"/>
				<xsd:element ref="private"/>
			</xsd:sequence>
		</xsd:complexType>
	</xsd:element>
	<xsd:element name="private">
		<xsd:complexType>
			<xsd:sequence>
				<xsd:element ref="include"/>
			</xsd:sequence>
		</xsd:complexType>
	</xsd:element>
	<xsd:element name="include" type="xsd:string"/>
	<xsd:element name="keyword" type="xsd:string"/>
	<xsd:element name="choice" type="xsd:string"/>
	<xsd:element name="link">
		<xsd:complexType>
			<xsd:simpleContent>
				<xsd:extension base="xsd:string">
					<xsd:attribute name="anchor" type="xsd:string" use="required"/>
				</xsd:extension>
			</xsd:simpleContent>
		</xsd:complexType>
	</xsd:element>
	<xsd:element name="return">
		<xsd:complexType>
			<xsd:attribute name="type" type="xsd:string" use="required"/>
		</xsd:complexType>
	</xsd:element>
	<xsd:element name="allowed">
		<xsd:complexType>
			<xsd:sequence>
				<xsd:element ref="value" maxOccurs="unbounded"/>
			</xsd:sequence>
			<xsd:attribute name="kind" type="xsd:string"/>
			<xsd:attribute name="type" type="xsd:string"/>
		</xsd:complexType>
	</xsd:element>
	<xsd:element name="comments">
		<xsd:complexType mixed="true">
			<xsd:sequence>
				<xsd:element ref="link" minOccurs="0"/>
			</xsd:sequence>
		</xsd:complexType>
	</xsd:element>
	<xsd:element name="range">
		<xsd:complexType>
			<xsd:attribute name="min" type="xsd:string" use="required"/>
			<xsd:attribute name="max" type="xsd:string" use="required"/>
		</xsd:complexType>
	</xsd:element>
	<xsd:element name="output">
		<xsd:complexType>
			<xsd:sequence>
				<xsd:element ref="param" maxOccurs="unbounded"/>
			</xsd:sequence>
		</xsd:complexType>
	</xsd:element>
	<xsd:element name="sub" type="xsd:string"/>
	<xsd:element name="sup" type="xsd:string"/>
	<xsd:element name="needs" type="xsd:string"/>
	<xsd:element name="comment">
		<xsd:complexType>
			<xsd:sequence>
				<xsd:element ref="method"/>
			</xsd:sequence>
		</xsd:complexType>
	</xsd:element>
	<xsd:element name="task">
		<xsd:complexType mixed="true">
			<xsd:sequence>
				<xsd:element ref="shortdescription" maxOccurs="unbounded"/>
				<xsd:element ref="input"/>
				<xsd:element ref="output" minOccurs="0"/>
				<xsd:element ref="returns" minOccurs="0"/>
				<xsd:element ref="description" minOccurs="0"/>
				<xsd:element ref="example"/>
			</xsd:sequence>
			<xsd:attribute name="type" type="xsd:string" use="required"/>
			<xsd:attribute name="name" type="xsd:string" use="required"/>
			<xsd:attribute name="category" type="xsd:string" use="required"/>
			<xsd:attribute name="visibility" type="xsd:string"/>
			<xsd:attribute name="async" type="xsd:string"/>
			<xsd:attribute name="startup" type="xsd:string"/>
		</xsd:complexType>
	</xsd:element>
	<xsd:element name="constraints">
		<xsd:complexType>
			<xsd:sequence>
				<xsd:element ref="when" minOccurs="0" maxOccurs="unbounded"/>
			</xsd:sequence>
		</xsd:complexType>
	</xsd:element>
	<xsd:element name="when">
		<xsd:complexType>
			<xsd:sequence>
				<xsd:element ref="notequals" minOccurs="0"/>
				<xsd:element ref="equals" minOccurs="0" maxOccurs="unbounded"/>
			</xsd:sequence>
			<xsd:attribute name="param" type="xsd:string" use="required"/>
		</xsd:complexType>
	</xsd:element>
	<xsd:element name="equals">
		<xsd:complexType>
			<xsd:sequence>
				<xsd:element ref="description" minOccurs="0"/>
				<xsd:element ref="value" minOccurs="0"/>
				<xsd:element ref="default" minOccurs="0" maxOccurs="unbounded"/>
			</xsd:sequence>
			<xsd:attribute name="type" type="xsd:string"/>
			<xsd:attribute name="value" type="xsd:string" use="required"/>
		</xsd:complexType>
	</xsd:element>
	<xsd:element name="default">
		<xsd:complexType>
			<xsd:sequence>
				<xsd:element ref="description" minOccurs="0"/>
				<xsd:element ref="value"/>
			</xsd:sequence>
			<xsd:attribute name="param" type="xsd:string" use="required"/>
			<xsd:attribute name="type" type="xsd:string"/>
		</xsd:complexType>
	</xsd:element>
	<xsd:element name="notequals">
		<xsd:complexType>
			<xsd:sequence>
				<xsd:element ref="default" maxOccurs="unbounded"/>
			</xsd:sequence>
			<xsd:attribute name="type" type="xsd:string"/>
			<xsd:attribute name="value" type="xsd:string" use="required"/>
		</xsd:complexType>
	</xsd:element>
	<xsd:element name="em" type="xsd:string"/>
</xsd:schema>

=== dic-case-studies/casa6/gcwrap/tasks/vishead.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet type="text/xsl" ?>

<casaxml xmlns="http://casa.nrao.edu/schema/psetTypes.html"
xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
xsi:schemaLocation="http://casa.nrao.edu/schema/casa.xsd
file:///opt/casa/code/xmlcasa/xml/casa.xsd">

<!-- Documentation here.                                                -->

<task type="function" name="vishead" category="information, manipulation">

<shortdescription>List, summary, get, and put metadata in a measurement set</shortdescription>
<description>List, summary, get, and put "header" information in a measurement set.</description>

<input>
    <param type="string" name="vis" kind="ms" mustexist="true">
        <description>Name of input visibility file</description>
        <value></value>
        <example>vis='ngc5921.ms'</example>
    </param>

    <param type="string" name="mode">
        <description>options: list, summary, get, put</description>
        <allowed kind="enum">
            <value>list</value>
            <value>summary</value>
            <value>get</value>
            <value>put</value>
            <value></value> 
        <!--<value>add</value>
            <value>del</value>-->
        </allowed>
        <value>summary</value>
        <example>mode=''->'list'; mode='get'</example>
    </param>

    <param type="stringArray" name="listitems" subparam="true">
      <description>items to list ([] for all)</description>
         <value type="stringArray">
                   <value type="string">telescope</value>
                   <value type="string">observer</value>
                   <value type="string">project</value>
                   <value type="string">field</value>
                   <value type="string">freq_group_name</value>
                   <value type="string">spw_name</value>
                   <value type="string">schedule</value>
                   <value type="string">schedule_type</value>
                   <value type="string">release_date</value>
         </value>
      <example>listitems = ['field', 'ptcs']; see help for list of keywords</example>
    </param>

    <param type="string" name="hdkey" subparam="true">
        <description>keyword to get/put</description>
        <value type="stringArray"></value>
        <example>hdkey='telescope'; see help for list of keywords</example>
    </param>

    <param type="string" name="hdindex" subparam="true">
        <description>keyword index to get/put, counting from zero. ''==>all</description>
        <value></value>
        <example>hdindex='3'; see help for list of keywords</example>
    </param>

    <param type="any" name="hdvalue" subparam="true">
        <any type="variant"/>
        <description>value of hdkey</description>
        <value type="string"></value>
        <example>hdvalue=['VLA','BIMA']</example>
    </param>

    <constraints>
          <when param="mode">
             <equals type="string" value="list">
           <default param="listitems">
         <value type="stringArray">
           <value type="string">'telescope'</value>
           <value type="string">'observer'</value>
           <value type="string">'project'</value>
           <value type="string">'field'</value>
           <value type="string">'freq_group_name'</value>
           <value type="string">'spw_name'</value>
           <value type="string">'schedule'</value>
           <value type="string">'schedule_type'</value>
           <value type="string">'release_date'</value>
         </value>
           </default>
         </equals>
             <equals type="string" value="summary"/>
             <equals type="string" value="get">
                   <default param="hdkey"><value type="string"/></default>
                   <default param="hdindex"><value type="string"/></default>
             </equals>
             <equals type="string" value="put">
                   <default param="hdkey"><value type="string"/></default>
                   <default param="hdindex"><value type="string"/></default>
                   <default param="hdvalue"><value type="string"/></default>
             </equals>
          </when>
    </constraints>

</input>

<!-- DIRTY HACK: <description> does not currently (2009-03-10) make it into help or ?,
                 but <example> does. -->
<!-- <description> -->
<example>

        This task allows the user to manipulate some meta-data parameters in a
        measurement set.  The mode='list' shows those keywords that are
        presently implemented, with their values.  The contents associated
        with the keywords can be obtained (get) and changed (put).

        The modes that are available are:

           list    --- List all keywords that are recognized, and list the
                       value(s) for each.  Only these keywords can be obtained
                       (get) or changed (put) 
           summary --- Equivalent to running taskname='listobs'; verbose=F
           get     --- Get the specified keyword value(s) from the ms
           put     --- Put the specified keyword value(s) into the ms

        Parameters currently implemented are (June 1, 2009):

           cal_grp              
           field                 Field names
           fld_code              Field Observing codes
           freq_group_name       
           log                   
           observer              Observer name
           project               Project name
           ptcs                  Phase tracking centers for each field
           release_date          
           schedule
           schedule_type
           spw_name              Spectral parameters?
           source_name           Source Names (=Field Names?)
           telescope             Telescope Name

        Keyword arguments:

        vis  --- Name of input visibility file
                  default: none, example: vis='my.ms'

        mode --- Mode of operation for vishead
                  default = 'list'; example: mode='get'

        hdkey--- keyword to get or put from the ms (used in get/put mode only)
                  ex: hdkey='telescope'

        hdindex--- index (counting from 0) if keyword is an array (used in get/put
                  mode only)
                  ex: hdindex='2'; hdindex=''->put/get full array; 

        hdvalue   --- value to be put in the MS (used in put mode only)
                  ex: hdvalue=array(['MyTelescope'])

<!-- </description> -->

<!-- <example> -->
        Examples:

           To transfer the parameters to useful python items requires some care.

           taskname = 'vishead'
           default() 
           vis = '3C84C.ms'
           mode = 'get'
                      
           to get a field name (string),
              hdkey = 'field'; hdindex = '2'; hdvalue=vishead(); 
                       print hdvalue[0] = the name for field='2'                    
                
           to get an phase center (number)
              hdkey = 'ptcs'; hdindex = '1'; hdvalue = vishead();
                       hdvalue[0][0] gives the ra, hdvalue[0][1] gives the dec in field '1'


           taskname = 'vishead'
           default() 
           vis = '3C84C.ms'
           mode = 'put'

          To change a string,

              hdkey = 'field'; hdindex = '2'; hdvalue = 'junk'; vishead()
                   field='2' is renamed 'junk'

          To change a number, (egs. ra of field=1 to 0.5 radian)
              is too complicated to figure out!
             

</example>

</task>

</casaxml>

=== dic-case-studies/casa6/gcwrap/tasks/importfits.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet type="text/xsl" ?>
<casaxml xmlns="http://casa.nrao.edu/schema/psetTypes.html"
      xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
      xsi:schemaLocation="http://casa.nrao.edu/schema/casa.xsd
      file:///opt/casa/code/xmlcasa/xml/casa.xsd">

      <task type="function" name="importfits" category="import/export">
    <shortdescription>Convert an image FITS file into a CASA image</shortdescription>
<description>
Convert an image FITS file into a CASA image
</description>
    <input>
        <param type="string" mustexist="true" name="fitsimage">
<shortdescription>Name of input image FITS file</shortdescription>
<description>Name of input image FITS file
                     Default: none

                        Example: fitsimage='3C273XC1.fits'
</description>
            <value></value>
        </param>

        <param type="string" name="imagename">
<shortdescription>Name of output CASA image</shortdescription>
<description>Name of output CASA image
                     Default: none

                        Example: fitsimage='3C273XC1.image'
</description>
            <value></value>
        </param>

        <param type="int" name="whichrep">
<shortdescription>If fits image has multiple coordinate reps, choose one.</shortdescription>
<description>If fits image has multiple coordinate reps, choose one.
                     Default: 0 (means first)

                        Example: whichrep=1
</description>
            <value>0</value>
        </param>

        <param type="int" name="whichhdu">
<shortdescription>If fits file contains multiple images, choose one (0 = first HDU, -1 = first valid image).</shortdescription>
<description>If fits file contains multiple images, choose one
                     Default: -1 (use the first valid one)

                     NOTE: 0 = first HDU, -1 = first valid image

                        Example: whichhdu=1
</description>
            <value>-1</value>
        </param>

        <param type="bool" name="zeroblanks">
<shortdescription>Set blanked pixels to zero (not NaN)</shortdescription>
<description>Set blanked pixels to zero (not NaN)
                     Default: True
                     Options: True|False
</description>
            <value>True</value>
        </param>

        <param type="bool" name="overwrite">
<shortdescription>Overwrite output file if it exists?</shortdescription>
 <description>Overwrite output file if it exists?
                     Default: False
                     Options: False|True
</description>
            <value>False</value>
        </param>

        <param type="bool" name="defaultaxes">
<shortdescription>Add the default 4D coordinate axes where they are missing; value True requires setting defaultaxesvalues</shortdescription>
<description>Add the default 4D coordinate axes where they are
missing
                     Default: False
                     Options: False|True

                     IMPORTANT: value True requires setting defaultaxesvalues
</description>
            <value>False</value>
        </param>

        <param type="variant" name="defaultaxesvalues">
<shortdescription>List of values to assign to added degenerate axes when defaultaxes==True (ra,dec,freq,stokes)</shortdescription>
<description>List of values to assign to added degenerate axes when
defaultaxes==True (ra,dec,freq,stokes)
                     Default: []

                     For existing axes, empty strings can be given as
                     values. For the directions and spectral values,
                     any valid angle/frequency expressions can be
                     given.

                        Example: defaultaxesvalues=['19h30m00',
                        '-02d30m00', '88.5GHz', 'Q'] 
</description>
            <value>[]</value>
        </param>

        <param type="variant" name="beam">
<shortdescription>List of values to be used to define the synthesized beam [BMAJ,BMIN,BPA] (as in the FITS keywords)</shortdescription>
<description>List of values to be used to define the synthesized beam
[BMAJ,BMIN,BPA] (as in the FITS keywords)
                     Default: [] (i.e.take from FITS file)

                        Example: beam=['0.35arcsec', '0.24arcsec',
                        '25deg']
</description>
            <value>[]</value>
        </param>
    </input>

<example>
FOR MORE INFORMATION, SEE THE TASK PAGES OF IMPORTFITS IN CASA DOCS:
https://casa.nrao.edu/casadocs/
 </example>
 </task>
 </casaxml>

=== dic-case-studies/casa6/casa5/gcwrap/tasks/viewer.xml
<casaxml xsi:schemaLocation="http://casa.nrao.edu/schema/casa.xsd       file:///opt/casa/code/xmlcasa/xml/casa.xsd" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns="http://casa.nrao.edu/schema/psetTypes.html">

<task async="never" category="visualization" name="viewer" type="function">
    <shortdescription>View an image or visibility data set</shortdescription>
    <description>
        The viewer will display images in raster, contour, vector or
        marker form.  Images can be blinked, and movies are available
        for spectral-line image cubes.  For measurement sets, many
        display and editing options are available.

        The viewer can be run outside of casapy by typing &lt;casaviewer&gt;.

        Executing viewer &lt;viewer&gt; will bring up a display panel
        window, which can be resized.  If no data file was specified,
        a Load Data window will also appear. Click on the desired data
        file and choose the display type; the rendered data should appear
        on the display panel.

        A Data Display Options window will also appear.  It has drop-down
        subsections for related options, most of which are self-explanatory.
          
        The state of the viewer -- loaded data and related display
        options -- can be saved in a 'restore' file for later use.
        You can provide the restore filename on the command line or
        select it from the Load Data window.

        See the cookbook for more details on using the viewer.
        
    </description>
    <input>
        <param allowblank="true" mustexist="true" name="infile" type="string"><shortdescription> (Optional)  Name of file to visualize.</shortdescription><description> (Optional)  Name of file to visualize.</description>
            
            <value/>
        </param>

        <param name="displaytype" type="string"><shortdescription> (Optional)  Type of visual rendering (raster, contour, vector or marker).  lel  if an lel expression is given for infile  (advanced).</shortdescription><description> (Optional)  Type of visual rendering (raster, contour, vector or marker).  lel  if an lel expression is given for infile  (advanced).</description>
            
            <value>raster</value>
        </param>

        <param name="channel" type="int"><shortdescription> (Optional)  access a specific channel in the image cube</shortdescription><description> (Optional)  access a specific channel in the image cube</description>
            
            <value>0</value>
        </param>

        <param name="zoom" type="int"><shortdescription> (Optional)  zoom in/out by increments</shortdescription><description> (Optional)  zoom in/out by increments</description>
            
            <value>1</value>
        </param>

        <param name="outfile" type="string"><shortdescription> (Optional)  name of the output file to generate</shortdescription><description> (Optional)  name of the output file to generate</description>
            
            <value/>
        </param>

        <param name="outscale" type="double"><shortdescription> (Optional)  amount to scale output bitmap formats (non-PS, non-PDF)</shortdescription><description> (Optional)  amount to scale output bitmap formats (non-PS, non-PDF)</description>
            
            <value>1.0</value>
        </param>

        <param name="outdpi" type="int"><shortdescription> (Optional)  output DPI for PS/PDF</shortdescription><description> (Optional)  output DPI for PS/PDF</description>
            
            <value>300</value>
        </param>

        <param name="outformat" type="string"><shortdescription> (Optional)  format of the output e.g. jpg or pdf (this is overridden by the output files extension</shortdescription><description> (Optional)  format of the output e.g. jpg or pdf (this is overridden by the output files extension</description>
            
            <value>jpg</value>
        </param>

        <param name="outlandscape" type="bool"><shortdescription> (Optional)  should the output mode be landscape (PS or PDF)</shortdescription><description> (Optional)  should the output mode be landscape (PS or PDF)</description>
            
            <value>False</value>
        </param>

        <param name="gui" type="bool"><shortdescription> (Optional)  Display the panel in a GUI.</shortdescription><description> (Optional)  Display the panel in a GUI.</description>
            
            <value>True</value>
        </param>

                <constraints>
                </constraints>
    </input>
    <returns type="void"/>

    <example>

        examples of usage:

        viewer
        viewer &quot;myimage.im&quot;
        viewer &quot;mymeasurementset.ms&quot;
        viewer &quot;myrestorefile.rstr&quot;
        
        viewer &quot;myimage.im&quot;, &quot;contour&quot;

        viewer &quot;'myimage1.im' - 2 * 'myimage2.im'&quot;, &quot;lel&quot;
        
        
        Keyword arguments:
        infile -- Name of file to visualize
                default: ''
                example: infile='ngc5921.image'
                If no infile is specified the Load Data window
                will appear for selecting data.
        displaytype -- (optional): method of rendering data
                visually (raster, contour, vector or marker).  
                You can also set this parameter to 'lel' and
                provide an lel expression for infile (advanced).
                default: 'raster'
                example: displaytype='contour'

        Note: the filetype parameter is optional; typing of
        data files is now inferred:
                example:  viewer infile='my.im'
                obsolete: viewer infile='my.im', filetype='raster'
        the filetype is still used to load contours, etc.

    </example>
</task>
</casaxml>
